// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20241205014710_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Aerodrom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KapacitetLetelica")
                        .HasColumnType("int");

                    b.Property<int>("KapacitetPutnika")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Aerodromi");
                });

            modelBuilder.Entity("WebTemplate.Models.Let", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojPutnika")
                        .HasColumnType("int");

                    b.Property<int?>("DolazniAerodromID")
                        .HasColumnType("int");

                    b.Property<int?>("LetelicaID")
                        .HasColumnType("int");

                    b.Property<int?>("PolazniAerodromID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremePoletanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeSletanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DolazniAerodromID");

                    b.HasIndex("LetelicaID");

                    b.HasIndex("PolazniAerodromID");

                    b.ToTable("Letovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Letelica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojMotora")
                        .HasColumnType("int");

                    b.Property<int>("BrojOsoblja")
                        .HasColumnType("int");

                    b.Property<int>("KapacitetPutnika")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Letelice");
                });

            modelBuilder.Entity("WebTemplate.Models.Let", b =>
                {
                    b.HasOne("WebTemplate.Models.Aerodrom", "DolazniAerodrom")
                        .WithMany("DolazniLetovi")
                        .HasForeignKey("DolazniAerodromID");

                    b.HasOne("WebTemplate.Models.Letelica", "Letelica")
                        .WithMany("Letovi")
                        .HasForeignKey("LetelicaID");

                    b.HasOne("WebTemplate.Models.Aerodrom", "PolazniAerodrom")
                        .WithMany("PolazniLetovi")
                        .HasForeignKey("PolazniAerodromID");

                    b.Navigation("DolazniAerodrom");

                    b.Navigation("Letelica");

                    b.Navigation("PolazniAerodrom");
                });

            modelBuilder.Entity("WebTemplate.Models.Aerodrom", b =>
                {
                    b.Navigation("DolazniLetovi");

                    b.Navigation("PolazniLetovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Letelica", b =>
                {
                    b.Navigation("Letovi");
                });
#pragma warning restore 612, 618
        }
    }
}
