// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using maj2021.Models;

#nullable disable

namespace maj2021.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250729125702_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("maj2021.Models.Fabrika", b =>
                {
                    b.Property<int>("FabrikaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabrikaID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FabrikaID");

                    b.ToTable("Fabrike");
                });

            modelBuilder.Entity("maj2021.Models.Silos", b =>
                {
                    b.Property<int>("SilosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SilosID"));

                    b.Property<int?>("FabrikaID")
                        .HasColumnType("int");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrenutnaKolicina")
                        .HasColumnType("int");

                    b.HasKey("SilosID");

                    b.HasIndex("FabrikaID");

                    b.ToTable("Silosi");
                });

            modelBuilder.Entity("maj2021.Models.Silos", b =>
                {
                    b.HasOne("maj2021.Models.Fabrika", null)
                        .WithMany("ListaSilosa")
                        .HasForeignKey("FabrikaID");
                });

            modelBuilder.Entity("maj2021.Models.Fabrika", b =>
                {
                    b.Navigation("ListaSilosa");
                });
#pragma warning restore 612, 618
        }
    }
}
