// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20241205202806_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Autor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("WebTemplate.Models.IzdavackaKuca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Drzava")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IzdavackeKuce");
                });

            modelBuilder.Entity("WebTemplate.Models.Knjiga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojStranica")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumObjavljivanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zanr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("WebTemplate.Models.Ugovor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AutorID")
                        .HasColumnType("int");

                    b.Property<int>("BrojUgovora")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPotpisivanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IzdavackaKucaID")
                        .HasColumnType("int");

                    b.Property<int?>("KnjigaFK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AutorID");

                    b.HasIndex("IzdavackaKucaID");

                    b.HasIndex("KnjigaFK")
                        .IsUnique()
                        .HasFilter("[KnjigaFK] IS NOT NULL");

                    b.ToTable("Ugovori");
                });

            modelBuilder.Entity("WebTemplate.Models.Ugovor", b =>
                {
                    b.HasOne("WebTemplate.Models.Autor", "Autor")
                        .WithMany("Ugovori")
                        .HasForeignKey("AutorID");

                    b.HasOne("WebTemplate.Models.IzdavackaKuca", "IzdavackaKuca")
                        .WithMany("Ugovori")
                        .HasForeignKey("IzdavackaKucaID");

                    b.HasOne("WebTemplate.Models.Knjiga", "Knjiga")
                        .WithOne("Ugovor")
                        .HasForeignKey("WebTemplate.Models.Ugovor", "KnjigaFK");

                    b.Navigation("Autor");

                    b.Navigation("IzdavackaKuca");

                    b.Navigation("Knjiga");
                });

            modelBuilder.Entity("WebTemplate.Models.Autor", b =>
                {
                    b.Navigation("Ugovori");
                });

            modelBuilder.Entity("WebTemplate.Models.IzdavackaKuca", b =>
                {
                    b.Navigation("Ugovori");
                });

            modelBuilder.Entity("WebTemplate.Models.Knjiga", b =>
                {
                    b.Navigation("Ugovor");
                });
#pragma warning restore 612, 618
        }
    }
}
