// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Fakultet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Fakulteti");
                });

            modelBuilder.Entity("WebTemplate.Models.Smer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("FakultetID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("FakultetID");

                    b.ToTable("Smerovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojIndeksa")
                        .HasColumnType("int");

                    b.Property<int?>("FakultetID")
                        .HasColumnType("int");

                    b.Property<int>("GodinaRodjenja")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("SmerID")
                        .HasColumnType("int");

                    b.Property<string>("SrednjaSkola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FakultetID");

                    b.HasIndex("SmerID");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("WebTemplate.Models.Upis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumUpisa")
                        .HasColumnType("datetime2");

                    b.Property<int>("ESPB")
                        .HasColumnType("int");

                    b.Property<int?>("FakultetID")
                        .HasColumnType("int");

                    b.Property<int?>("SmerID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FakultetID");

                    b.HasIndex("SmerID");

                    b.HasIndex("StudentID");

                    b.ToTable("Upisi");
                });

            modelBuilder.Entity("WebTemplate.Models.Smer", b =>
                {
                    b.HasOne("WebTemplate.Models.Fakultet", "Fakultet")
                        .WithMany("Smerovi")
                        .HasForeignKey("FakultetID");

                    b.Navigation("Fakultet");
                });

            modelBuilder.Entity("WebTemplate.Models.Student", b =>
                {
                    b.HasOne("WebTemplate.Models.Fakultet", "Fakultet")
                        .WithMany("Studenti")
                        .HasForeignKey("FakultetID");

                    b.HasOne("WebTemplate.Models.Smer", "Smer")
                        .WithMany()
                        .HasForeignKey("SmerID");

                    b.Navigation("Fakultet");

                    b.Navigation("Smer");
                });

            modelBuilder.Entity("WebTemplate.Models.Upis", b =>
                {
                    b.HasOne("WebTemplate.Models.Fakultet", "Fakultet")
                        .WithMany("Upisi")
                        .HasForeignKey("FakultetID");

                    b.HasOne("WebTemplate.Models.Smer", "Smer")
                        .WithMany()
                        .HasForeignKey("SmerID");

                    b.HasOne("WebTemplate.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");

                    b.Navigation("Fakultet");

                    b.Navigation("Smer");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WebTemplate.Models.Fakultet", b =>
                {
                    b.Navigation("Smerovi");

                    b.Navigation("Studenti");

                    b.Navigation("Upisi");
                });
#pragma warning restore 612, 618
        }
    }
}
