// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using decembar2023.Models;

#nullable disable

namespace decembar2023.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250717212908_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("decembar2023.Models.Prodavnica", b =>
                {
                    b.Property<int>("ProdavnicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdavnicaID"));

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ProdavnicaID");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("decembar2023.Models.Proizvod", b =>
                {
                    b.Property<int>("ProizodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizodID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("DostupnaKolicina")
                        .HasColumnType("int");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.HasKey("ProizodID");

                    b.HasIndex("ProdavnicaID");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("decembar2023.Models.Proizvod", b =>
                {
                    b.HasOne("decembar2023.Models.Prodavnica", null)
                        .WithMany("ListaProizvoda")
                        .HasForeignKey("ProdavnicaID");
                });

            modelBuilder.Entity("decembar2023.Models.Prodavnica", b =>
                {
                    b.Navigation("ListaProizvoda");
                });
#pragma warning restore 612, 618
        }
    }
}
