// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ocene.Models;

#nullable disable

namespace Ocene.Migrations
{
    [DbContext(typeof(OceneContext))]
    partial class OceneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ocene.Models.Ocena", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PredmetFK")
                        .HasColumnType("int");

                    b.Property<int?>("StudentFK")
                        .HasColumnType("int");

                    b.Property<int>("Vrednost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PredmetFK");

                    b.HasIndex("StudentFK");

                    b.ToTable("Ocene");
                });

            modelBuilder.Entity("Ocene.Models.Predmet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("Ocene.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImePrezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Indeks")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("Ocene.Models.Ocena", b =>
                {
                    b.HasOne("Ocene.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetFK");

                    b.HasOne("Ocene.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentFK");

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
