// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20241208120545_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojKoloseka")
                        .HasColumnType("bigint");

                    b.Property<long>("BrojStanovnika")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Relacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojPutnika")
                        .HasColumnType("bigint");

                    b.Property<long>("CenaKarte")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DolazniGradID")
                        .HasColumnType("int");

                    b.Property<int?>("PolazniGradID")
                        .HasColumnType("int");

                    b.Property<int?>("VozID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DolazniGradID");

                    b.HasIndex("PolazniGradID");

                    b.HasIndex("VozID");

                    b.ToTable("Relacije");
                });

            modelBuilder.Entity("WebTemplate.Models.Voz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumProizvodnje")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaksimalnaBrzina")
                        .HasColumnType("bigint");

                    b.Property<long>("MaksimalnaTezina")
                        .HasColumnType("bigint");

                    b.Property<long>("MaksimalniKapacitet")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vozovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Relacija", b =>
                {
                    b.HasOne("WebTemplate.Models.Grad", "DolazniGrad")
                        .WithMany("DolazneRelacije")
                        .HasForeignKey("DolazniGradID");

                    b.HasOne("WebTemplate.Models.Grad", "PolazniGrad")
                        .WithMany("PolazneRelacija")
                        .HasForeignKey("PolazniGradID");

                    b.HasOne("WebTemplate.Models.Voz", "Voz")
                        .WithMany("Relacije")
                        .HasForeignKey("VozID");

                    b.Navigation("DolazniGrad");

                    b.Navigation("PolazniGrad");

                    b.Navigation("Voz");
                });

            modelBuilder.Entity("WebTemplate.Models.Grad", b =>
                {
                    b.Navigation("DolazneRelacije");

                    b.Navigation("PolazneRelacija");
                });

            modelBuilder.Entity("WebTemplate.Models.Voz", b =>
                {
                    b.Navigation("Relacije");
                });
#pragma warning restore 612, 618
        }
    }
}
